cat 64/dat_ach.json | base64 -d > dat_ach.json 
cat 64/dat_act.json | base64 -d > dat_act.json 
cat 64/dat_ap.json | base64 -d > dat_ap.json 
cat 64/dat_att.json | base64 -d > dat_att.json 
cat 64/dat_buf.json | base64 -d > dat_buf.json 
cat 64/dat_cat.json | base64 -d > dat_cat.json 
cat 64/dat_cit.json | base64 -d > dat_cit.json 
cat 64/dat_cla_0.json | base64 -d > dat_cla_0.json 
cat 64/dat_cla_1.json | base64 -d > dat_cla_1.json 
cat 64/dat_cla_2.json | base64 -d > dat_cla_2.json 
cat 64/dat_cre.json | base64 -d > dat_cre.json 
cat 64/dat_dia.json | base64 -d > dat_dia.json 
cat 64/dat_ele.json | base64 -d > dat_ele.json 
cat 64/dat_enm.json | base64 -d > dat_enm.json 
cat 64/dat_leg.json | base64 -d > dat_leg.json 
cat 64/dat_mis.json | base64 -d > dat_mis.json 
cat 64/dat_rea.json | base64 -d > dat_rea.json 
cat 64/dat_sta.json | base64 -d > dat_sta.json 
cat 64/dat_tuts.json | base64 -d > dat_tuts.json