import { EquipableItemTypeData } from '../model/equipable-item-type-data';

export const EQUIPABLE_ITEM_DATA: { [key: string]: { [key: string]: EquipableItemTypeData } } = {
    armor: {
        "atk_mag-atk_phy": { name: 'chainmail vest' },
        "atk_phy-def_phy": { name: 'chainmail plated armor' },
        "atk_phy-def_mag": { name: 'chainmail breastplate' },
        "atk_phy-def_dodge": { name: 'chainmail brigandine coat' },
        "atk_phy-ret": { name: 'jagged armor' },
        "atk_phy-life": { name: 'assault armor' },
        "atk_phy-mana": { name: 'mystic armor' },
        "atk_mag-def_phy": { name: 'sumptuous plated armor' },
        "atk_mag-def_mag": { name: 'sumptuous breastplate' },
        "atk_mag-def_dodge": { name: 'sumptuous brigandine coat' },
        "atk_mag-ret": { name: 'jagged vest' },
        "atk_mag-life": { name: 'assault vest' },
        "atk_mag-mana": { name: 'mystic vest' },
        "def_phy-def_phy": { name: 'iron plated armor' },
        "def_mag-def_phy": { name: 'splendid plated armor' },
        "def_dodge-def_phy": { name: 'light plated armor' },
        "def_phy-ret": { name: 'rusty plated armor' },
        "def_phy-life": { name: 'siege plated armor' },
        "def_phy-mana": { name: 'runic plated armor' },
        "def_mag-def_mag": { name: 'splendid breastplate' },
        "def_dodge-def_mag": { name: 'light breastplate' },
        "def_mag-ret": { name: 'rusty breastplate' },
        "def_mag-life": { name: 'siege breastplate' },
        "def_mag-mana": { name: 'runic breastplate' },
        "def_dodge-def_dodge": { name: 'light brigandine coat' },
        "def_dodge-ret": { name: 'rusty brigandine coat' },
        "def_dodge-life": { name: 'siege brigandine coat' },
        "def_dodge-mana": { name: 'runic brigandine coat' },
        "life-ret": { name: 'assault jagged chestguard' },
        "mana-ret": { name: 'mystic jagged chestguard' },
        "life-mana": { name: 'assault clothing' },
    },
    amulet: {
        "mana": { name: 'mystic pendant' },
        "ret": { name: 'jagged amulet' },
        "def_phy": { name: 'iron locket' },
        "def_mag": { name: 'splendid talisman' },
        "atk_mag": { name: 'sumptuous pendant' },
        "atk_phy": { name: 'chainmail necklace' },
        "adventure": { name: 'dragonskin necklace' },
        "def_dodge": { name: 'light amulet' },
        "life": { name: 'assault locket' },
        "minion": { name: 'bone talisman' },
    },
    belt: {
        "def_mag": { name: 'splendid belt' },
        "def_phy": { name: 'iron waistguard' },
        "atk_phy": { name: 'chainmail belt' },
        "crit": { name: 'great strap' },
        "def_alt": { name: 'plated waistguard' },
        "aura": { name: 'haunted band' },
        "spd": { name: 'brisk strap' },
        "atk_mag": { name: 'sumptuous band' },
        "ret": { name: 'jagged wrap' },
        "def_dodge": { name: 'light wrap' },
    }
}