export enum UltimatumType {
    InfiniteWisdom = 0,
    IndisputedSpeed = 1,
    AdamantAbundance = 2,
    EndlessWealth = 3,
    EchoingBeyond = 4,
    ProfoundDepth = 5,
    PerfectSegmentation = 6,
    ImpeccableTechnique = 7,
    FlawlessPower = 8,
    SplendidHorizon = 9,
    ProdigiousCalamity = 10,
    MarvelousJudgment = 11,
    PerpendicularParallelism = 12,
    DivineIntervention = 13,
    StoicWrath = 14,
}

export const ALL_ULTIMATUM_TYPES = [
    UltimatumType.InfiniteWisdom,
    UltimatumType.IndisputedSpeed,
    UltimatumType.AdamantAbundance,
    UltimatumType.EndlessWealth,
    UltimatumType.EchoingBeyond,
    UltimatumType.ProfoundDepth,
    UltimatumType.PerfectSegmentation,
    UltimatumType.ImpeccableTechnique,
    UltimatumType.FlawlessPower,
    UltimatumType.SplendidHorizon,
    UltimatumType.ProdigiousCalamity,
    UltimatumType.MarvelousJudgment,
    UltimatumType.PerpendicularParallelism,
    UltimatumType.DivineIntervention,
    UltimatumType.StoicWrath,
]